// Copyright Contributors to the KubeOpenCode project

// Package v1alpha1 contains the v1alpha1 API definitions
package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ContextType defines the type of context source
// +kubebuilder:validation:Enum=Text;ConfigMap;Git;Runtime;Secret;URL
type ContextType string

const (
	// ContextTypeText represents text content defined directly in YAML.
	ContextTypeText ContextType = "Text"

	// ContextTypeConfigMap represents content from a ConfigMap
	ContextTypeConfigMap ContextType = "ConfigMap"

	// ContextTypeGit represents content from a Git repository
	ContextTypeGit ContextType = "Git"

	// ContextTypeRuntime represents KubeOpenCode platform awareness context.
	// When enabled, the controller injects a system prompt that explains
	// the runtime environment to the agent.
	ContextTypeRuntime ContextType = "Runtime"

	// ContextTypeSecret represents content from a Kubernetes Secret.
	// Unlike Credentials (which are for agent authentication), Secret contexts
	// provide content for the AI agent to read and process as task input.
	//
	// Use cases:
	//   - Configuration templates containing sensitive values
	//   - API specifications with embedded credentials
	//   - License files or certificates the agent needs to read
	ContextTypeSecret ContextType = "Secret"

	// ContextTypeURL represents content fetched from a remote HTTP/HTTPS URL.
	// The content is fetched at task execution time via an init container.
	//
	// Use cases:
	//   - Remote API specifications (OpenAPI, GraphQL schemas)
	//   - External documentation or guidelines
	//   - Dynamic configuration from external services
	ContextTypeURL ContextType = "URL"
)

// ConfigMapContext references a ConfigMap for context content.
type ConfigMapContext struct {
	// Name of the ConfigMap
	// +required
	Name string `json:"name"`

	// Key specifies a single key to mount as a file.
	// If not specified, all keys are mounted as files in the directory.
	// +optional
	Key string `json:"key,omitempty"`

	// Optional specifies whether the ConfigMap must exist.
	// +optional
	Optional *bool `json:"optional,omitempty"`
}

// GitContext references content from a Git repository.
type GitContext struct {
	// Repository is the Git repository URL.
	// Example: "https://github.com/org/contexts"
	// +required
	Repository string `json:"repository"`

	// Path is the path within the repository to mount.
	// Can be a file or directory. If empty, the entire repository is mounted.
	//
	// Note on .git directory:
	//   - If Path is empty (entire repo): The mounted directory WILL contain .git/
	//   - If Path is specified (subdirectory): The mounted directory will NOT contain .git/
	//
	// Example: ".claude/", "docs/guide.md"
	// +optional
	Path string `json:"path,omitempty"`

	// Ref is the Git reference (branch, tag, or commit SHA).
	// Defaults to "HEAD" if not specified.
	// +optional
	// +kubebuilder:default="HEAD"
	Ref string `json:"ref,omitempty"`

	// Depth specifies the clone depth for shallow cloning.
	// 1 means shallow clone (fastest), 0 means full clone.
	// Defaults to 1 for efficiency.
	// +optional
	// +kubebuilder:default=1
	Depth *int `json:"depth,omitempty"`

	// SecretRef references a Secret containing Git credentials.
	// The Secret should contain one of:
	//   - "username" + "password": For HTTPS token-based auth (password can be a PAT)
	//   - "ssh-privatekey": For SSH key-based auth
	// If not specified, anonymous clone is attempted.
	// +optional
	SecretRef *GitSecretReference `json:"secretRef,omitempty"`
}

// GitSecretReference references a Secret for Git authentication.
type GitSecretReference struct {
	// Name of the Secret containing Git credentials.
	// +required
	Name string `json:"name"`
}

// RuntimeContext enables KubeOpenCode platform awareness for agents.
// When enabled, the controller injects a system prompt that explains:
//   - The agent is running in a Kubernetes environment as a KubeOpenCode Task
//   - Available environment variables (TASK_NAME, TASK_NAMESPACE, WORKSPACE_DIR)
//   - How to query Task/Workflow information via kubectl
//   - Understanding of task.md structure and context mounting
//
// This context type has no configurable fields - the content is generated
// by the controller at runtime.
type RuntimeContext struct {
	// No fields - content is generated by the controller
}

// SecretContext references a Kubernetes Secret for context content.
// This is different from Credentials: Credentials are for agent authentication
// (env vars, mounted files), while SecretContext provides content for the agent
// to read and process as part of the task.
type SecretContext struct {
	// Name of the Secret
	// +required
	Name string `json:"name"`

	// Key specifies a single key to use from the Secret.
	// If not specified, all keys are mounted as files in the directory
	// (requires MountPath to be set on ContextItem).
	// +optional
	Key string `json:"key,omitempty"`
}

// URLContext references content from a remote HTTP/HTTPS URL.
// The content is fetched at task execution time via an init container.
type URLContext struct {
	// Source is the URL to fetch content from.
	// Must be a valid HTTP or HTTPS URL.
	// +required
	Source string `json:"source"`

	// Headers specifies HTTP headers to include in the request.
	// Useful for authentication tokens or custom headers.
	// Example: {"Authorization": "Bearer token123"}
	// +optional
	Headers map[string]string `json:"headers,omitempty"`

	// SecretRef references a Secret containing authentication credentials.
	// The Secret can contain:
	//   - "token": Used as Bearer token in Authorization header
	//   - "username" + "password": Used for HTTP Basic authentication
	// If both Headers["Authorization"] and SecretRef are specified,
	// SecretRef takes precedence.
	// +optional
	SecretRef *URLSecretReference `json:"secretRef,omitempty"`

	// InsecureSkipTLSVerify skips TLS certificate verification.
	// WARNING: This is insecure and should only be used for testing
	// or with self-signed certificates in controlled environments.
	// +optional
	InsecureSkipTLSVerify bool `json:"insecureSkipTLSVerify,omitempty"`

	// Timeout specifies the request timeout in seconds.
	// Defaults to 30 seconds if not specified.
	// +optional
	// +kubebuilder:default=30
	Timeout *int32 `json:"timeout,omitempty"`
}

// URLSecretReference references a Secret for URL authentication.
type URLSecretReference struct {
	// Name of the Secret containing authentication credentials.
	// +required
	Name string `json:"name"`
}

// ContextItem defines context with content and mount path.
// Used directly in Task/Agent specs to provide additional context for task execution.
type ContextItem struct {
	// === Common Fields ===

	// Name is an optional identifier for this context.
	// Used for:
	//   - Logging and debugging (clearer error messages)
	//   - XML tag generation (appears in task.md context blocks)
	//   - Context deduplication (same-named contexts can override each other)
	// If not specified, a default name is generated based on the context type and index.
	// +optional
	Name string `json:"name,omitempty"`

	// Description provides human-readable documentation for this context.
	// This is purely for documentation purposes and does not affect behavior.
	// Useful for explaining why a context is included or what it provides.
	// +optional
	Description string `json:"description,omitempty"`

	// Optional specifies whether this context is required for task execution.
	// If true, the task will proceed even if the context cannot be resolved
	// (e.g., ConfigMap not found, Git clone failed, URL fetch failed).
	// If false (default), the task will fail if the context cannot be resolved.
	//
	// Note: This field takes precedence over type-specific optional fields
	// (e.g., configMap.optional). If both are specified, this field wins.
	// +optional
	Optional *bool `json:"optional,omitempty"`

	// === Type and Mount Configuration ===

	// Type of context source: Text, ConfigMap, Git, Runtime, Secret, or URL
	// +required
	Type ContextType `json:"type"`

	// MountPath specifies where this context should be mounted in the agent pod.
	//
	// Path resolution follows Tekton conventions:
	// - Absolute paths (starting with "/") are used as-is
	// - Relative paths (NOT starting with "/") are prefixed with the agent's workspaceDir
	//
	// If not specified, the content is appended to task.md with XML tags.
	//
	// Note: For Runtime context type, MountPath is ignored - content is always
	// appended to task.md.
	// +optional
	MountPath string `json:"mountPath,omitempty"`

	// FileMode is the file permission mode for the mounted file (e.g., 0755 for executable scripts).
	// Only applicable when MountPath is specified.
	// If not specified, defaults to 0644.
	// +optional
	FileMode *int32 `json:"fileMode,omitempty"`

	// === Type-Specific Fields ===

	// Text is the text content (required when Type == "Text").
	// Contains text content defined directly in YAML.
	// +optional
	Text string `json:"text,omitempty"`

	// ConfigMap context (required when Type == "ConfigMap")
	// +optional
	ConfigMap *ConfigMapContext `json:"configMap,omitempty"`

	// Git context (required when Type == "Git")
	// +optional
	Git *GitContext `json:"git,omitempty"`

	// Runtime context (optional when Type == "Runtime")
	// Enables KubeOpenCode platform awareness. The controller injects a system prompt
	// that explains the runtime environment to the agent.
	// +optional
	Runtime *RuntimeContext `json:"runtime,omitempty"`

	// Secret context (required when Type == "Secret")
	// References a Kubernetes Secret for context content.
	// Unlike Credentials, this provides content for the agent to read and process.
	// +optional
	Secret *SecretContext `json:"secret,omitempty"`

	// URL context (required when Type == "URL")
	// Fetches content from a remote HTTP/HTTPS URL at task execution time.
	// +optional
	URL *URLContext `json:"url,omitempty"`
}

// TaskPhase represents the current phase of a task
// +kubebuilder:validation:Enum=Pending;Queued;Running;Completed;Failed
type TaskPhase string

const (
	// TaskPhasePending means the task has not started yet
	TaskPhasePending TaskPhase = "Pending"
	// TaskPhaseQueued means the task is waiting for Agent capacity.
	// This occurs when the Agent has maxConcurrentTasks set and the limit is reached.
	// The task will automatically transition to Running when capacity becomes available.
	TaskPhaseQueued TaskPhase = "Queued"
	// TaskPhaseRunning means the task is currently executing
	TaskPhaseRunning TaskPhase = "Running"
	// TaskPhaseCompleted means the task execution finished (Job exited with code 0).
	// This indicates the agent completed its work, not necessarily that the task "succeeded".
	// The actual outcome should be determined by examining the agent's output.
	TaskPhaseCompleted TaskPhase = "Completed"
	// TaskPhaseFailed means the task had an infrastructure failure
	// (e.g., Job crashed, unable to schedule, missing Agent).
	TaskPhaseFailed TaskPhase = "Failed"
)

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope="Namespaced",shortName=tk
// +kubebuilder:printcolumn:JSONPath=`.status.phase`,name="Phase",type=string
// +kubebuilder:printcolumn:JSONPath=`.status.podName`,name="Pod",type=string
// +kubebuilder:printcolumn:JSONPath=`.metadata.creationTimestamp`,name="Age",type=date

// Task represents a single task execution.
// Task is the primary API for users who want to execute AI-powered tasks.
type Task struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec defines the desired state of Task
	Spec TaskSpec `json:"spec"`

	// Status represents the current status of the Task
	// +optional
	Status TaskExecutionStatus `json:"status,omitempty"`
}

// TaskSpec defines the Task configuration
type TaskSpec struct {
	// Description is the task instruction/prompt.
	// The controller creates ${WORKSPACE_DIR}/task.md with this content
	// (where WORKSPACE_DIR is configured in Agent.spec.workspaceDir, defaulting to "/workspace").
	// This is the primary way to tell the agent what to do.
	//
	// Example:
	//   description: "Update all dependencies and create a PR"
	// +optional
	Description *string `json:"description,omitempty"`

	// Contexts provides additional context for the task.
	// Contexts are processed in array order, with later contexts taking precedence.
	//
	// Context priority (lowest to highest):
	//   1. Agent.contexts (Agent-level defaults)
	//   2. Task.contexts (Task-specific contexts)
	//   3. Task.description (highest, becomes ${WORKSPACE_DIR}/task.md)
	//
	// Example:
	//   contexts:
	//     - type: Text
	//       text: "Always use conventional commits"
	//     - type: Git
	//       mountPath: src
	//       git:
	//         repository: https://github.com/org/repo
	//         ref: main
	// +optional
	Contexts []ContextItem `json:"contexts,omitempty"`

	// AgentRef references an Agent for this task.
	// If not specified, uses the "default" Agent in the same namespace.
	// +optional
	AgentRef string `json:"agentRef,omitempty"`

	// Outputs defines output parameters specific to this Task.
	// These are merged with Agent.spec.outputs (Task takes precedence).
	//
	// Merge behavior:
	//   - Parameters with same name: Task definition overrides Agent
	//   - Parameters with different names: Both are kept
	//
	// Example:
	//   Agent defines: pr-url, summary
	//   Task defines: summary (different path), custom-metric
	//   Result: pr-url (from Agent), summary (from Task), custom-metric (from Task)
	// +optional
	Outputs *OutputSpec `json:"outputs,omitempty"`
}

// TaskExecutionStatus defines the observed state of Task
type TaskExecutionStatus struct {
	// ObservedGeneration is the most recent generation observed by the controller.
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// Execution phase
	// +optional
	Phase TaskPhase `json:"phase,omitempty"`

	// Kubernetes Pod name
	// +optional
	PodName string `json:"podName,omitempty"`

	// Start time
	// +optional
	StartTime *metav1.Time `json:"startTime,omitempty"`

	// Completion time
	// +optional
	CompletionTime *metav1.Time `json:"completionTime,omitempty"`

	// Outputs contains results captured from task execution.
	// This is populated when the task completes (either success or failure).
	// +optional
	Outputs *TaskOutputs `json:"outputs,omitempty"`

	// Kubernetes standard conditions
	// +optional
	// +listType=map
	// +listMapKey=type
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// TaskOutputs contains parameters captured from task execution files.
// The output-collector sidecar reads files specified in OutputSpec and
// writes the captured values to the Pod's termination message.
//
// Size limits (due to Kubernetes termination message 4KB limit):
//   - Total JSON output: max 4KB
//   - For larger outputs, consider using external storage (future feature)
type TaskOutputs struct {
	// Parameters is a key-value map of outputs captured from files.
	// Keys are defined in Agent.spec.outputs and Task.spec.outputs.
	// Values are read from the corresponding file paths by the sidecar.
	//
	// Example usage:
	//   kubectl get task my-task -o jsonpath='{.status.outputs.parameters.pr-url}'
	// +optional
	Parameters map[string]string `json:"parameters,omitempty"`
}

// OutputSpec defines output parameters to capture from task execution.
// Used by both Agent (defaults) and Task (overrides).
// The controller merges Agent and Task outputs, with Task taking precedence.
type OutputSpec struct {
	// Parameters defines the output parameters to capture from files.
	// Each parameter specifies a name and file path to read from.
	// +optional
	Parameters []OutputParameterSpec `json:"parameters,omitempty"`
}

// OutputParameterSpec defines a single output parameter to capture from a file.
type OutputParameterSpec struct {
	// Name is the parameter name, used as the key in status.outputs.parameters.
	// Must be unique within the merged output parameters.
	// +required
	Name string `json:"name"`

	// Path is the file path to read the parameter value from.
	// Relative paths are prefixed with workspaceDir.
	// Example: ".outputs/pr-url" -> ${WORKSPACE_DIR}/.outputs/pr-url
	// +required
	Path string `json:"path"`

	// Default is the default value if the file doesn't exist.
	// If not specified and file doesn't exist, parameter is omitted from output.
	// +optional
	Default *string `json:"default,omitempty"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// TaskList contains a list of Task
type TaskList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Task `json:"items"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope="Namespaced",shortName=ag
// +kubebuilder:printcolumn:JSONPath=`.spec.agentImage`,name="Image",type=string,priority=1
// +kubebuilder:printcolumn:JSONPath=`.spec.serviceAccountName`,name="ServiceAccount",type=string
// +kubebuilder:printcolumn:JSONPath=`.metadata.creationTimestamp`,name="Age",type=date

// Agent defines the AI agent configuration for task execution.
// Agent = AI agent + permissions + tools + infrastructure
// This is the execution black box - Task creators don't need to understand execution details.
type Agent struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec defines the agent configuration
	Spec AgentSpec `json:"spec"`

	// Status represents the current status of the Agent
	// +optional
	Status AgentStatus `json:"status,omitempty"`
}

// AgentSpec defines agent configuration
type AgentSpec struct {
	// AgentImage specifies the OpenCode init container image.
	// This image contains the OpenCode binary that gets copied to /tools volume.
	// The init container runs this image and copies the opencode binary to /tools/opencode.
	// If not specified, defaults to "quay.io/kubeopencode/kubeopencode-agent-opencode:latest".
	// +optional
	AgentImage string `json:"agentImage,omitempty"`

	// ExecutorImage specifies the main worker container image for task execution.
	// This is the development environment where tasks actually run.
	// The container uses /tools/opencode (provided by agentImage init container) to execute AI tasks.
	// If not specified, defaults to "quay.io/kubeopencode/kubeopencode-agent-devbox:latest".
	// +optional
	ExecutorImage string `json:"executorImage,omitempty"`

	// WorkspaceDir specifies the working directory inside the agent container.
	// This is where task.md and context files are mounted.
	// The agent image must support the WORKSPACE_DIR environment variable.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Pattern=`^/.*`
	// +kubebuilder:validation:MinLength=1
	WorkspaceDir string `json:"workspaceDir"`

	// Command specifies the entrypoint command for the agent container.
	// This is REQUIRED and overrides the default ENTRYPOINT of the container image.
	//
	// The command defines HOW the agent executes tasks. Different users can
	// customize execution behavior (e.g., output format, flags) without
	// modifying the agent image. The agent image only provides the tools.
	//
	// ## Example
	//
	//   command: ["sh", "-c", "gemini --yolo -p \"$(cat /workspace/task.md)\""]
	//
	// +required
	// +kubebuilder:validation:MinItems=1
	Command []string `json:"command"`

	// Contexts provides default contexts for all tasks using this Agent.
	// These have the lowest priority in context merging.
	//
	// Context priority (lowest to highest):
	//   1. Agent.contexts (Agent-level defaults)
	//   2. Task.contexts (Task-specific contexts)
	//   3. Task.description (highest, becomes ${WORKSPACE_DIR}/task.md)
	//
	// Use this for organization-wide defaults like coding standards, security policies,
	// or common tool configurations that should apply to all tasks.
	// +optional
	Contexts []ContextItem `json:"contexts,omitempty"`

	// Credentials defines secrets that should be available to the agent.
	// Similar to GitHub Actions secrets, these can be mounted as files or
	// exposed as environment variables.
	//
	// Example use cases:
	//   - GitHub token for repository access (env: GITHUB_TOKEN)
	//   - SSH keys for git operations (file: ~/.ssh/id_rsa)
	//   - API keys for external services (env: ANTHROPIC_API_KEY)
	//   - Cloud credentials (file: ~/.config/gcloud/credentials.json)
	// +optional
	Credentials []Credential `json:"credentials,omitempty"`

	// PodSpec defines advanced Pod configuration for agent pods.
	// This includes labels, scheduling, runtime class, and other Pod-level settings.
	// Use this for fine-grained control over how agent pods are created.
	// +optional
	PodSpec *AgentPodSpec `json:"podSpec,omitempty"`

	// ServiceAccountName specifies the Kubernetes ServiceAccount to use for agent pods.
	// This controls what cluster resources the agent can access via RBAC.
	//
	// The ServiceAccount must exist in the same namespace where tasks are created.
	// Users are responsible for creating the ServiceAccount and appropriate RBAC bindings
	// based on what permissions their agent needs.
	//
	// +required
	ServiceAccountName string `json:"serviceAccountName"`

	// MaxConcurrentTasks limits the number of Tasks that can run concurrently
	// using this Agent. When the limit is reached, new Tasks will enter Queued
	// phase until capacity becomes available.
	//
	// This is useful when the Agent uses backend AI services with rate limits
	// (e.g., Claude, Gemini API quotas) to prevent overwhelming the service.
	//
	// - nil or 0: unlimited (default behavior, no concurrency limit)
	// - positive number: maximum number of Tasks that can be in Running phase
	//
	// Example:
	//   maxConcurrentTasks: 3  # Only 3 Tasks can run at once
	// +optional
	MaxConcurrentTasks *int32 `json:"maxConcurrentTasks,omitempty"`

	// Outputs defines default output parameters for tasks using this Agent.
	// These can be overridden or extended by Task.spec.outputs.
	// The controller creates a sidecar to capture these outputs from files.
	//
	// Merge behavior with Task.spec.outputs:
	//   - Parameters with same name: Task definition overrides Agent
	//   - Parameters with different names: Both are kept
	//
	// Example:
	//   outputs:
	//     parameters:
	//       - name: pr-url
	//         path: ".outputs/pr-url"
	//       - name: summary
	//         path: ".outputs/summary"
	//         default: "No summary provided"
	// +optional
	Outputs *OutputSpec `json:"outputs,omitempty"`
}

// AgentStatus defines the observed state of Agent
type AgentStatus struct {
	// ObservedGeneration is the most recent generation observed by the controller.
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`

	// Conditions represent the latest available observations of the Agent's state.
	// +optional
	// +listType=map
	// +listMapKey=type
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// AgentPodSpec defines advanced Pod configuration for agent pods.
// This groups all Pod-level settings that control how the agent container runs.
type AgentPodSpec struct {
	// Labels defines additional labels to add to the agent pod.
	// These labels are applied to the Job's pod template and enable integration with:
	//   - NetworkPolicy podSelector for network isolation
	//   - Service selector for service discovery
	//   - PodMonitor/ServiceMonitor for Prometheus monitoring
	//   - Any other label-based pod selection
	//
	// Example: To make pods match a NetworkPolicy with podSelector:
	//   labels:
	//     network-policy: agent-restricted
	// +optional
	Labels map[string]string `json:"labels,omitempty"`

	// Scheduling defines pod scheduling configuration for agent pods.
	// This includes node selection, tolerations, and affinity rules.
	// +optional
	Scheduling *PodScheduling `json:"scheduling,omitempty"`

	// RuntimeClassName specifies the RuntimeClass to use for agent pods.
	// RuntimeClass provides a way to select container runtime configurations
	// such as gVisor (runsc) or Kata Containers for enhanced isolation.
	//
	// This is useful when running untrusted AI agent code that may generate
	// and execute arbitrary commands. Using gVisor or Kata provides an
	// additional layer of security beyond standard container isolation.
	//
	// The RuntimeClass must exist in the cluster before use.
	// Common values: "gvisor", "kata", "runc" (default if not specified)
	//
	// Example:
	//   runtimeClassName: gvisor
	//
	// See: https://kubernetes.io/docs/concepts/containers/runtime-class/
	// +optional
	RuntimeClassName *string `json:"runtimeClassName,omitempty"`
}

// PodScheduling defines scheduling configuration for agent pods.
// All fields are applied directly to the Job's pod template.
type PodScheduling struct {
	// NodeSelector specifies a selector for scheduling pods to specific nodes.
	// The pod will only be scheduled to nodes that have all the specified labels.
	//
	// Example:
	//   nodeSelector:
	//     kubernetes.io/os: linux
	//     node-type: gpu
	// +optional
	NodeSelector map[string]string `json:"nodeSelector,omitempty"`

	// Tolerations allows pods to be scheduled on nodes with matching taints.
	//
	// Example:
	//   tolerations:
	//     - key: "dedicated"
	//       operator: "Equal"
	//       value: "ai-workload"
	//       effect: "NoSchedule"
	// +optional
	Tolerations []corev1.Toleration `json:"tolerations,omitempty"`

	// Affinity specifies affinity and anti-affinity rules for pods.
	// This enables advanced scheduling based on node attributes, pod co-location,
	// or pod anti-affinity for high availability.
	//
	// Example:
	//   affinity:
	//     nodeAffinity:
	//       requiredDuringSchedulingIgnoredDuringExecution:
	//         nodeSelectorTerms:
	//           - matchExpressions:
	//               - key: topology.kubernetes.io/zone
	//                 operator: In
	//                 values: ["us-west-2a", "us-west-2b"]
	// +optional
	Affinity *corev1.Affinity `json:"affinity,omitempty"`
}

// Credential represents a secret that should be available to the agent.
// Each credential references a Kubernetes Secret and specifies how to expose it.
//
// Mounting behavior depends on whether SecretRef.Key is specified:
//
// 1. No Key specified + No MountPath: entire Secret as environment variables
// 2. No Key specified + MountPath: entire Secret as directory (each key becomes a file)
// 3. Key specified + Env: single key as environment variable
// 4. Key specified + MountPath: single key as file
type Credential struct {
	// Name is a descriptive name for this credential (for documentation purposes).
	// +required
	Name string `json:"name"`

	// SecretRef references the Kubernetes Secret containing the credential.
	// +required
	SecretRef SecretReference `json:"secretRef"`

	// MountPath specifies where to mount the secret.
	// - If SecretRef.Key is specified: mounts the single key's value as a file at this path.
	//   Example: "/home/agent/.ssh/id_rsa" for SSH keys
	// - If SecretRef.Key is not specified: mounts the entire Secret as a directory,
	//   where each key in the Secret becomes a file in the directory.
	//   Example: "/etc/ssl/certs" for a Secret containing ca.crt, client.crt, client.key
	// +optional
	MountPath *string `json:"mountPath,omitempty"`

	// Env specifies the environment variable name to expose the secret value.
	// Only applicable when SecretRef.Key is specified.
	// If specified, the secret key's value is set as this environment variable.
	// Example: "GITHUB_TOKEN" for GitHub API access
	// +optional
	Env *string `json:"env,omitempty"`

	// FileMode specifies the permission mode for mounted files.
	// Only applicable when MountPath is specified.
	// Defaults to 0600 (read/write for owner only) for security.
	// Use 0400 for read-only files like SSH keys.
	// +optional
	FileMode *int32 `json:"fileMode,omitempty"`
}

// SecretReference references a Kubernetes Secret.
// When Key is specified, only that specific key is used.
// When Key is omitted, the entire Secret is used (behavior depends on Credential.MountPath).
type SecretReference struct {
	// Name of the Secret.
	// +required
	Name string `json:"name"`

	// Key of the Secret to select.
	// If not specified, the entire Secret is used:
	// - With MountPath: mounted as a directory (each key becomes a file)
	// - Without MountPath: all keys become environment variables
	// When Key is omitted, the Env field on the Credential is ignored.
	// +optional
	Key *string `json:"key,omitempty"`
}

// ConfigMapKeySelector selects a key of a ConfigMap.
type ConfigMapKeySelector struct {
	// Name of the ConfigMap
	// +required
	Name string `json:"name"`

	// Key of the ConfigMap to select from
	// +required
	Key string `json:"key"`

	// Specify whether the ConfigMap must be defined
	// +optional
	Optional *bool `json:"optional,omitempty"`
}

// ConfigMapReference references an entire ConfigMap.
// Used with DirPath to mount all keys as files in a directory.
type ConfigMapReference struct {
	// Name of the ConfigMap
	// +required
	Name string `json:"name"`

	// Specify whether the ConfigMap must be defined
	// +optional
	Optional *bool `json:"optional,omitempty"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// AgentList contains a list of Agent
type AgentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Agent `json:"items"`
}

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:resource:scope="Namespaced",shortName=ktc
// +kubebuilder:printcolumn:JSONPath=`.metadata.creationTimestamp`,name="Age",type=date

// KubeOpenCodeConfig defines system-level configuration for KubeOpenCode.
// This CRD provides cluster or namespace-level settings for the KubeOpenCode system.
type KubeOpenCodeConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec defines the KubeOpenCode configuration
	Spec KubeOpenCodeConfigSpec `json:"spec"`
}

// KubeOpenCodeConfigSpec defines the system-level configuration
type KubeOpenCodeConfigSpec struct {
	// SystemImage configures the KubeOpenCode system image used for internal components
	// such as git-init and context-init containers.
	// If not specified, uses the built-in default image with IfNotPresent policy.
	// +optional
	SystemImage *SystemImageConfig `json:"systemImage,omitempty"`
}

// SystemImageConfig configures the KubeOpenCode system image used for internal components
// such as git-init and context-init containers.
type SystemImageConfig struct {
	// Image specifies the system image to use for internal KubeOpenCode components.
	// If not specified, defaults to the built-in DefaultKubeOpenCodeImage.
	// Example: "quay.io/kubeopencode/kubeopencode:v0.2.0"
	// +optional
	Image string `json:"image,omitempty"`

	// ImagePullPolicy specifies the image pull policy for the system image.
	// Defaults to IfNotPresent if not specified.
	// +optional
	// +kubebuilder:validation:Enum=Always;Never;IfNotPresent
	ImagePullPolicy corev1.PullPolicy `json:"imagePullPolicy,omitempty"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// KubeOpenCodeConfigList contains a list of KubeOpenCodeConfig
type KubeOpenCodeConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []KubeOpenCodeConfig `json:"items"`
}
